## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
android.enableJetifier=false
android.nonFinalResIds=false
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.jvm.target.validation.mode=IGNORE
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx5120m -XX:+UseParallelGC
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.unsafe.configuration-cache=false
ksp.useKSP2=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.usesSdkInManifest.disallowed=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
isFullBuild=false
